# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

# Список всіх Python файлів проекту
a = Analysis(
    ['bot.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('data.json', '.'),
        ('projects.json', '.'),
        ('browser_profile', 'browser_profile'),
        ('*.md', '.'),
    ],
    hiddenimports=[
        'telegram',
        'telegram.ext',
        'telegram.ext.filters',
        'aiohttp',
        'requests',
        'selenium',
        'selenium.webdriver',
        'selenium.webdriver.chrome',
        'selenium.webdriver.chrome.service',
        'selenium.webdriver.chrome.options',
        'selenium.webdriver.common.by',
        'selenium.webdriver.support.ui',
        'selenium.webdriver.support.wait',
        'selenium.webdriver.support.expected_conditions',
        'selenium.common.exceptions',
        'dotenv',
        'asyncio',
        'threading',
        'logging',
        'datetime',
        'json',
        'os',
        'sys',
        'pathlib',
        'typing',
        'security_manager',
        'project_manager',
        'discord_monitor',
        'twitter_monitor',
        'selenium_twitter_monitor',
        'config',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='telegram_monitor_bot',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
